#ifndef QTXLMODULAR_GLOBAL_H
#define QTXLMODULAR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTXLMODULAR_LIBRARY)
#  define QTXLMODULARSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTXLMODULARSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTXLMODULAR_GLOBAL_H
